### ISSUE TITLE
Network connection error messaging

### ISSUE THREAD

**Issue by chris-whittick** [okta/okta-signin-widget#361] opened 2017-12-11 13:45 UTC
If there is a CORS issue or if the user can't access the Okta org (blocked by proxy etc) the first time they enter the username password, it displayed the generic error message "We found some errors. Please review the form and make corrections." if you press it again you will see the proper error "Unable to connect to the server. Please check your network connection."

Is there a way to get the right error to show first properly? Seems to be who is triggering hte error the model vs the primary auth form.

**Comment by chris-whittick-vgh** [comment] 2017-12-11 15:13
I think the route cause is I do not supply an error function to the renderEl(...) 

I am seeing if this will fix it, seems to a case when testing locally.

**Comment by santhoshbalakrishnan** [comment] 2018-01-23 21:28
@chris-whittick-vgh From a fresh clone of the repo, we show up an alert asking to check if CORS is enabled.

<img width="530" alt="screen shot 2018-01-23 at 1 27 24 pm" src="https://user-images.githubusercontent.com/24683447/35301702-1502a2a2-0041-11e8-804e-e75317e05c24.png">

We have the error case that throws out this alert here: https://github.com/okta/okta-signin-widget/blob/master/buildtools/templates/index.tpl#L66

Did you get a chance to fix it already?

**Comment by nbarbettini** [comment] 2018-06-12 19:54
Not having an error handler was indeed the root cause of this. In https://github.com/okta/okta-signin-widget/pull/466 we added a default error handler, so even if you don't specify an error handler, you get the behavior you expect (logging an error to the console on unrecoverable errors).

If you run into more issues like this, please file them here. Thanks for reporting it! 👍

**Comment by santhoshbalakrishnan** [comment] 2018-06-13 00:37
Closing out the issue this was resolved with https://github.com/okta/okta-signin-widget/pull/466.

**Closed by santhoshbalakrishnan** 2018-06-13 00:37 UTC

**Comment by bkoprivi** [comment] 2018-09-20 20:17
> Not having an error handler was indeed the root cause of this. In #466 we added a default error handler, so even if you don't specify an error handler, you get the behavior you expect (logging an error to the console on unrecoverable errors).
> 
> If you run into more issues like this, please file them here. Thanks for reporting it!

So you are that smart arse who program a code without error handling. If you were a medical doctor, you would be banned for life to practice medicine. But hey, source code can withstand anything, all sorts of shyte
