### ISSUE TITLE
Unhandled Rejection (OAuthError): The client specified not to prompt, but the user is not logged in.

### ISSUE THREAD

**Issue by amok** [okta/okta-signin-widget#952] opened 2019-11-07 14:24 UTC
### Background info

After some time of inactivity (>1h) I reload the page and Okta throws an error.

### Expected behavior

At least to be abele to initialize Okta and check session expired.

### What went wrong?

The error happens initializing Okta, on `new OktaSignIn(...`

```
Unhandled Rejection (OAuthError): The client specified not to prompt, but the user is not logged in.
```

https://monosnap.com/file/OvEvAzeyemVYfX4gQ8yZBlMCPi4OPE

When I reload the page again I get redirected to sign-in page

### Steps to reproduce

1) sign in
2) be inactive for a some time (>1h or so)
3) reload the page
4) experience the error

### Your environment

  - Okta Sign-In Widget Version: 3.4.0 (https://global.oktacdn.com/okta-signin-widget/3.4.0/js/okta-sign-in.min.js)
  - Browser: Chrome Canary (Version 80.0.3960.0 (Official Build) canary (64-bit))
  - OS: macOS Catalina (Version 10.15.1 (19B88))
  - Language: en-US

May be related to https://github.com/okta/okta-oidc-js/issues/567

**Comment by aarongranick-okta** [comment] 2020-03-16 21:17
@amok We have made some updates which we think may have fixed this issue. Can you confirm if the issue is still present with the current version of the Signin Widget (3.8.1)? We would like to see this issue resolved.

**Comment by amok** [comment] 2020-03-16 22:17
Thanks for replying @aarongranick-okta . Will check reopen the issue in case problem persist.

**Comment by joebailey26** [comment] 2020-03-29 11:52
I have experienced the same problem. 

I have now updated to okta-vue 1.3.0 and okta-auth-js 3.0.0. 

The problem still occurs after >1 hour of inactivity: refresh the page and a blank screen, chrome has some messages about Okta cookies being set without same site. These messages don't display when the user is logged in correctly and the app is functioning, however, the "client specified not to prompt" console error is now gone. 

Issue #567 and #460 are similar.

**Comment by joebailey26** [comment] 2020-03-29 17:47
You can replicate the issue by changing the system clock to be forward in time thus making the token invalid. Vue then doesn't render anything, it seems like the navigation guard no longer functions. The user can get out of this blank screen by manually navigating to the login page.

**Comment by amok** [comment] 2020-03-29 18:04
@joebailey26 is reporting that the issue persists, so I'm reopening the issue

**Comment by joebailey26** [comment] 2020-03-30 16:29
Seems like my app is getting confused between the development and production callback URLs. When the cache is cleared Vue Okta Login passes the localhost URL to okta.com/oauth2/default/v1/token and when the cache is stale, when the error happens, trying to login results in an error as the app encodes the production URL to okta.com/oauth2/default/v1/token rather than the development URL

**Comment by joebailey26** [comment] 2020-03-30 22:51
Interestingly enough the error code: "error.errorCode: login_required, error.description: The client specified not to prompt, but the user is not logged in." came back just now.

**Comment by joebailey26** [comment] 2020-03-30 22:54
The redirect uri is stored in the Okta-PKCE-Storage in local storage is that of the production URL rather than the development URL. Clearing only the Okta-Cache-Storage seems to allow the user to log in though. Strange indeed.

**Comment by swiftone** [comment] 2020-04-10 21:16
@joebailey26 - Thanks for the details.  Two questions:
- Are you using the okta vue SDK, or just a Vue app?
- Is this an issue that a end-user encounters, or one that devs would only encounter?

**Comment by joebailey26** [comment] 2020-04-11 11:46
I'm using the Okta Vue SDK.

It's an issue end-users encounter.

This issue, however, now seems to have disappeared. I'm facing a similar issue where users will be redirected to Okta's hosted login randomly rather than directed to the app's login screen.

**Comment by swiftone** [comment] 2020-04-17 19:15
@joebailey26 
- Is this happening during initial login, or randomly during application use?
- Is this happening when your code calls to convert a `sessionToken`?

**Comment by joebailey26** [comment] 2020-04-17 22:00
This is happening when a user returns to the application after some inactivity and is required to login again. Sometimes the app's login screen is displayed. Sometimes the user is redirected to Okta's login.

I'm unsure of when it occurs as it is so random.

**Comment by joebailey26** [comment] 2020-04-20 10:46
Seeing this console error when directed to the Okta hosted login page: **error.errorCode: login_required, error.description: The client specified not to prompt, but the user is not logged in.**

**Comment by joebailey26** [comment] 2020-04-21 21:42
![Okta_Capture_1](https://user-images.githubusercontent.com/18091947/79916069-00797080-8420-11ea-834d-e4e858276731.png)

Managed to capture a screenshot of the errors. 

I know about the "cannot read property 'color' of undefined" that's to do with my app. 

The interesting ones are the login_required errors which occurred before and resulted in the blank screen. Now instead of the blank screen, you get directed to the Okta hosted login page.

**Comment by swiftone** [comment] 2020-04-21 22:12
@joebailey26 - I think we are narrowing this down.

I will need to check to see if our Vue examples have a similar issue, but we recently uncovered a bug in some of our React examples that caused exactly the issue you describe (login on the the Okta site as opposed to their app).

You can see the fix to the example here: https://github.com/okta/okta-developer-docs/pull/1125/files

The updated code sample is here: https://developer.okta.com/code/react/okta_react/. (Note the two places where the comments mention sessionToken)

If this code doesn't resemble yours, please provide some detail or contact our support team at developers@okta.com with whom you can private share details about your use-case.

**Comment by joebailey26** [comment] 2020-04-21 22:58
My code pretty much resembles the Okta Vue Sample found here: [https://github.com/okta/samples-js-vue/blob/master/custom-login/src/components/Login.vue](https://github.com/okta/samples-js-vue/blob/master/custom-login/src/components/Login.vue)

**Comment by joebailey26** [comment] 2020-04-22 18:09
When trying to login via the okta hosted login I only get as far as the callback page on my application. 

The following console errors are logged:

- **Failed to load resource: the server responded with a status of 400 ()** for the URL: [...okta.com/oauth2/default/v1/token](...okta.com/oauth2/default/v1/token)

- **[Vue warn]: Error in beforeMount hook (Promise/async): "AuthApiError" found in ---> ImplicitCallback > at ImplicitCallback.vue <App> at src/App.vue  <Root>**

**Comment by swiftone** [comment] 2020-04-24 18:58
@joebailey26 - sorry to need another clarification: You said your code resembles the sample of the custom-login, but then listed symptoms using the okta-hosted case.

You mentioned a 400 error - are there any details in the browser network dev tool in the body of the 400 response?

Lastly - this is happening with PKCE, which is definitely more time sensitive.  Have you confirmed that this happens on machines that are within a reasonably narrow boundary of temporal drift?

**Comment by swiftone** [comment] 2020-04-24 19:02
For Vue autoRenew issues
Internal ref: OKTA-293153

**Comment by joebailey26** [comment] 2020-04-24 21:43
I've used the custom login for my app, but the issue is: the user is occasionally (when they have been away from the app for a long time and come back) redirected to the login page hosted with Okta.

This is the response message for the 400 error: **{"error":"invalid_grant","error_description":"PKCE verification failed."}**

How could I confirm that this happens on machines with a narrow boundary of temporal drift?

**Comment by swiftone** [comment] 2020-05-08 18:53
@joebailey26 - I've been able to reproduce your case (once, but then not again), so I've added that to our internal ticket.

If you're not deliberately setting machine times to different values and are using some form of centralized time management (most networks do), then that's not the issue.  I brought it up only because we've had cases where developers were explicitly changing their system times.

**Comment by joebailey26** [comment] 2020-05-08 18:56
I'm glad you could replicate the issue. It seems to happen about once a day so is hard to catch.

Ahh okay. No, we're not setting specific times on our machines.

Will the issue still be tracked here on GitHub whilst the Okta team solve the bug?

**Comment by dchinu97** [comment] 2020-07-03 06:44
Any updates on this? I am facing similar issue once the access token has expired I am redirected to Okta Login instead want to redirect to the Custom Login page embedded in my vue application

**Comment by dchinu97** [comment] 2020-07-03 08:56
I was able to fix the flow by using 
![image](https://user-images.githubusercontent.com/26546015/86451874-203ee600-bd39-11ea-8df6-5b74414b51d0.png)

The onSessionExpired() Method overrides the default flow.

**Comment by ctben** [comment] 2020-07-04 20:17
> onSessionExpired

Where is this function?

**Comment by joebailey26** [comment] 2020-07-05 10:30
I too would like to know @dchinu97

**Comment by dchinu97** [comment] 2020-07-05 11:30
@ctben @joebailey26  Please find the details here 

https://github.com/okta/okta-oidc-js/tree/master/packages/okta-vue

![image](https://user-images.githubusercontent.com/26546015/86531625-8ade5600-bee0-11ea-8645-f308c9adee62.png)

This function has to be added in okta config similar to this

![image](https://user-images.githubusercontent.com/26546015/86531688-004a2680-bee1-11ea-97a1-745c35f95494.png)

**Comment by joebailey26** [comment] 2020-07-10 16:29
@dchinu97's solution worked for me

**Comment by dchinu97** [comment] 2020-07-13 12:54
@joebailey26  Okta Stored 2 type of token 1. Access Token 2. ID Token. The above only works for access token expiration. To Solve the overall Problem, the isAuthenticated() Methods also have to override by a custom one

**Comment by dchinu97** [comment] 2020-07-22 04:11
@amok  @swiftone @joebailey26  Can we close this issue? As the overriding above-mentioned callback methods solve the issue

**Comment by joebailey26** [comment] 2020-07-22 08:44
I think we can close

**Closed** 2020-07-22 11:22 UTC
Labels: awaiting-response
