### ISSUE TITLE
Password Managers fill out form says form is blank.

### ISSUE THREAD

**Issue by chris-whittick** [okta/okta-signin-widget#272] opened 2017-08-02 02:16 UTC
When using a plug in that submits passwords the form thinks it is blank unless I enter each box and hit an arrow key first to register a key press.

**Comment by therealnicksaunders** [comment] 2017-08-07 17:21
This is a common problem with JavaScript libraries that provide data-binding features; I think the plugin probably sets the input elements' _value_ properties without triggering an _input_ event. (If that's the case, it's more of a bug with the plugin, which isn't properly simulating user input, than with the sign-in widget.)

But in any case, I'm sure you'll be asked for the browser, plugin name, and corresponding version numbers.

**Comment by chris-whittick-vgh** [comment] 2017-10-11 13:50
Has this ever been looked at? Any advice here? It has been a couple of months. Should I get this escalated as an internal support case to get help with this issue?

**Comment by therealnicksaunders** [comment] 2017-10-11 14:24
What password manager are you using? What browser?

**Comment by chris-whittick-vgh** [comment] 2017-10-11 14:27
Wait you are an okta employee? 

IE, Chrome, Thycotics chrome plugins, Last pass, some sort of biometric finger print one, I am not sure the extra name.

**Comment by therealnicksaunders** [comment] 2017-10-11 15:47
I mean, I'm trying to help you out by helping you answer some basic questions for them. Reproducing the problem is always the first troubleshooting step, which you must already know as a technology professional. By the way, you're going to have to be way more precise with your answers, or I'm pretty sure they won't be able to help you. A little cordiality wouldn't hurt either.

I apologize for apparently intruding in a _private_ conversation in a public forum. I will stay out of it from now on.

**Comment by chris-whittick-vgh** [comment] 2017-10-11 16:18
Sorry Nick.

I didn't mean to be harsh to you. Just frustrated lately with the non response from the Okta devs, when a product is sold to someone with the suggested a direction of using this widget and then an issue can ignored for months. 

We have contributed to this project with functionality we needed that we thought would be useful to others, so we wanted to try to stay the OSS route in regards to the libraries we have been using rather than just sending in cases internally.

**Comment by therealnicksaunders** [comment] 2017-10-11 16:31
Thanks for the response. I do understand the frustration with these guys. I actually have our build process tweaking the source to fix some obscure CSS and JavaScript bugs! But, hey, my company is all-in with Okta! 😂

**Comment by mraible** [comment] 2017-10-11 21:21
> Just frustrated lately with the non response from the Okta devs, when a product is sold to someone with the suggested a direction of using this widget and then an issue can ignored for months.

@chris-whittick-vgh Hello Chris. My name is Matt Raible and I'm part of the Developer Relations team at Okta. Like you, I'm a developer, and I've experienced similar pain when trying to get things fixed with the Sign-In Widget - and I *work* for the company. The main problem is this project is run like an internal closed-source project, rather than a community-driven open source project. We're trying to change that internally.

**Comment by aarongranick-okta** [comment] 2020-03-16 18:59
This issue is a couple years old. Has the issue been corrected in subsequent versions?

**Comment by swiftone** [comment] 2020-04-03 20:58
Closing as stale.  If this continues to be a problem with the latest version, feel free to reopen with details.

**Closed by swiftone** 2020-04-03 20:58 UTC
Labels: awaiting-response
