### ISSUE TITLE
Error callback not called on a 401

### ISSUE THREAD

**Issue by fabioduque** [okta/okta-signin-widget#261] opened 2017-07-12 19:23 UTC
Hi!

I've recently started to work with this widget and when I enter the incorrect credentials on the login form, I receive a 401 on the console (which is expected):

`POST https://------.oktapreview.com/api/v1/authn 401 (Unauthorized)`

However, the **failure callback is not being invoked**. The success cb is working properly, though.

On the documentation ( [https://developer.okta.com/code/javascript/okta_sign-in_widget_ref](https://developer.okta.com/code/javascript/okta_sign-in_widget_ref) ), you specify that the function `renderEl` receives 3 arguments: config object, success callback and failure callback.

Can anyone else confirm that the same happens?

I am currently using v1.11.0, btw.

Thank you for your help!

**Comment by fabioduque** [comment] 2017-07-13 10:06
I think I've missed this part:

```
The widget will handle most types of errors - for example, if the user
enters an invalid password or there are issues authenticating.

This function is invoked with errors the widget cannot recover from:
1. Known errors: CONFIG_ERROR, UNSUPPORTED_BROWSER_ERROR, OAUTH_ERROR
2. Uncaught exceptions
```

So, this means that the widget will not invoke the callback on an invalid password.

Is there any other way to hook into this and know when we get a 401?
Via events, maybe? I just see the "pageRendered" event on the documentation and no other one.

If this is not possible, please see this as a suggestion to implement in the future.
Thank you!

**Comment by santhoshbalakrishnan** [comment] 2017-12-06 01:26
Duplicate of #181

**Closed by santhoshbalakrishnan** 2017-12-06 01:26 UTC
Labels: enhancement
