### ISSUE TITLE
Introduce a event for before the page starts rendering

### ISSUE THREAD

**Issue by omgitstom** [okta/okta-signin-widget#457] opened 2018-05-18 04:38 UTC
There is a flash of content when detecting page changes:

```
    signIn.on('pageRendered', function (data) {
      if (data.page == "password-expired") {
          window.location = "https://google.com";
      }
    });
```

We need an event to be fired before the page starts rendering for people that want to override behavior before it loads.

**Comment by jmelberg-okta** [comment] 2018-09-29 00:00
Closing as a duplicate of #539 - as we'll be tracking engineering work there.

**Comment by haishengwu-okta** [comment] 2018-11-16 00:32
@omgitstom 

Do you have examples / background why people want to override behavior and what they want to do themselves instead of using signin widget default behavior?

**Comment by nbarbettini** [comment] 2019-01-15 23:49
The `ready` event will provide this functionality, and is being released in [2.15](https://github.com/okta/okta-signin-widget/milestone/1).

**Closed by nbarbettini** 2019-01-15 23:49 UTC
