### ISSUE TITLE
iOS PWA State Transitions

### ISSUE THREAD

**Issue by matthewdfleming** [okta/okta-signin-widget#771] opened 2019-07-29 00:31 UTC
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Angular 7 application using the sign-in successfully (across many environments and browsers). The only environment so far that doesn't seem to totally work seamlessly is when our app (a PWA) is installed in iOS (added to home screen).

### Expected behavior

That the widget behave as in every other environment. 

### What went wrong?

The state transitions within the widget do not seem to fire until I interact with the screen.. So once I sign in.. the widget starts spinning but won't move to the next state (let's say login success) unless I push on the screen. If I put in a wrong password, the wrong password doesn't show up.. if the user needs an MFA, that won't show.

 It's like I have to trigger an event for the widget to move to the next state.

This works in every other environment and I cannot reproduce it outside of an installed PWA (so it's difficult for me to troubleshoot and narrow down the issue for you).

It looks like the callback functions aren't being called at all until some screen interaction.

Yes the guts of the callbacks are wrapped in an ngZone.run() call (so it's not that). I also have console logging (attempting to make sure it isn't an Angular thing) and those don't print.

Also the rest of the app outside of this widget works perfectly fine.

### Steps to reproduce

I'd love to create this but it's a bit of a big lift.. My app runs perfectly fine. It is accessible from the public internet but I don't want to post the address here (contact me if you want to see it).

### Your environment

  - Okta Sign-In Widget Version: 3.0.6
  - Browser: Safari PWA
  - OS: iOS
  - Language: Typescript

**Comment by matthewdfleming** [comment] 2019-07-29 13:19
Just an update.. I decided to try simulating a touch event on the widget to see what would happen. It looks like this work around seems to address the issue. I hope this will give you some more information about the nature of the problem.

```
this.subscription = timer(1000, 1000).subscribe(() => {
    const e = new Event('touchstart');
    document.getElementById('okta-login-container').dispatchEvent(e);
});
```

**Comment by bordecal** [comment] 2019-09-19 12:09
I see the same problem in version 3.2.1, but only when using `okta-sign-in.min.js`.  The problem is not present when importing the widget using the [bundling approach](https://developer.okta.com/code/javascript/okta_sign-in_widget/#bundling-the-widget).

**Comment by matthewdfleming** [comment] 2019-09-19 14:00
I originally switched to import the min due to the [development mode issue](https://github.com/okta/okta-signin-widget/issues/624). Do you see the debug log for the widget like I do if you use the bundle?

**Comment by bordecal** [comment] 2019-09-19 15:09
@matthewdfleming Yup.  'Tis annoying.  (It was also one of our main drivers for switching to `min.js`.)

**Comment by swiftone** [comment] 2019-09-25 21:59
@matthewdfleming , @bordecal - I have nothing helpful to add at the moment, but we appreciate your sharing, and the conversation has caused some renewed interest in https://github.com/okta/okta-signin-widget/issues/624

Just wanted to mention that you aren't being ignored, though I'm sure the delay is frustrating.

Regarding PWA: We have no advice outside of the work-around above at this time, but any other interested parties should be sure to 👍 the issue.

**Comment by matthewdfleming** [comment] 2019-09-26 13:46
So I decided that this issue was more critical than #624. I put the import back to `import * as OktaSignIn from '@okta/okta-signin-widget';`. I can confirm that this issue does seem to go away with that import.

@swiftone the [instructions in the bundling guide](https://developer.okta.com/code/javascript/okta_sign-in_widget/#bundling-the-widget) also seem slightly off as I get different errors (I forget what it is now, it's hard to keep track) if I follow the instructions to the letter and use `import OktaSignIn from '@okta/okta-signin-widget';`. Likewise the [example app that you guys put out to demo OIDC](https://github.com/okta/samples-js-angular/blob/master/custom-login/src/app/login/login.component.ts) has the `import * as OktaSignIn` form. 

Not sure what that's about but it would be nice to have at least one single source as the gold standard 'example' that we could follow. As an aside, the sample angular app also shows #624.

**Comment by aarongranick-okta** [comment] 2019-10-02 21:38
@matthewdfleming Since you are using typescript, try turning on `esModuleInterop` this should eliminate the need for `import *`

**Comment by swiftone** [comment] 2019-10-21 20:04
Closing this issue as it appears to be build-process/import dependent, and we currently have no explicit support for PWA.  If the issue arises again outside of the import issues, please open a new issue and reference this one.

**Closed by swiftone** 2019-10-21 20:04 UTC
Labels: enhancement, workaround-available
