### ISSUE TITLE
Unsafe eval

### ISSUE THREAD

**Issue by roberttenbrincke** [okta/okta-signin-widget#408] opened 2018-03-14 10:59 UTC
This widget requires the 'unsafe-eval' CSP header to be added (or the use of a nonce-based approach) in order to work correctly. Is it possible to make the widget operate without resorting to eval()?

Further investigation suggests this is caused by Handlebars.

**Comment by nbarbettini** [comment] 2018-03-26 18:19
It's not possible to avoid eval() right now. This is due to how the widget uses Handlebars internally (as you noticed).

We're investigating how to remove this requirement. It 's a longer-term project, but it is on our radar.

**Comment by roberttenbrincke** [comment] 2018-04-04 13:44
Handlebars offers recompilation. Would that be a viable route?

**Comment by XaxisJosh** [comment] 2019-10-21 15:13
any updates on this?

**Comment by swiftone** [comment] 2019-10-21 20:37
@XaxisJosh - Thanks for the followup.  No updates at the moment (it remains on our radar) but the issue is getting more attention (see also https://github.com/okta/okta-signin-widget/issues/902 ).

If this issue accumulates enough +1s and/or our business unit sees enough demand, this will rise in priority.

**Comment by omgitstom** [comment] 2020-01-10 21:05
https://github.com/wycats/handlebars.js/blob/master/FAQ.md#why-doesnt-this-work-with-content-security-policy-restrictions

**Comment by haishengwu-okta** [comment] 2020-02-13 17:44
https://github.com/wycats/handlebars.js/issues/1443

**Comment by bretterer** [comment] 2020-02-14 22:01
internal ref: OKTA-156161

**Comment by CPedrini** [comment] 2020-06-25 17:59
Any update?

**Comment by aarongranick-okta** [comment] 2020-06-26 19:35
@CPedrini The changes have been implemented internally and we are currently testing it. We expect to release a CSP-compliant widget soon.

**Comment by zustellr** [comment] 2020-08-13 08:08
@aarongranick-okta do you have more information on when "soon" is expected to be? Thanks!

**Comment by aarongranick-okta** [comment] 2020-08-14 00:20
@zustellr @CPedrini @afalahi @XaxisJosh @roberttenbrincke This has been released. Try updating widget to the latest version, let us know how it goes!

**Comment by matthew-borland** [comment] 2020-10-29 15:06
FYI I was just now using version 4.5.2 of the Okta signin widget, and I appeared to still have this problem.  I will take a further look at this.

**Comment by matthew-borland** [comment] 2020-10-29 15:18
OK, I verified CSP without unsafe-eval appears to work with this version; sorry for the confusion!

**Comment by swiftone** [comment] 2020-10-29 15:36
Closing issue as confirmed fixed

**Closed by swiftone** 2020-10-29 15:36 UTC
Labels: enhancement, priority-pending

**Comment by melcor76** [comment] 2021-03-10 11:35
> OK, I verified CSP without unsafe-eval appears to work with this version; sorry for the confusion!

Hi, how did you solve your issue after it appeared to not be working?
I'm on 4.5.2 and getting this error and tried everything I can come up with.
Like deleting node_modules and lock file and doing a prod build.

![image](https://user-images.githubusercontent.com/4782776/110623353-05145800-819d-11eb-9192-63dc6c140cf2.png)

**Comment by melcor76** [comment] 2021-03-10 12:27
This is not working in 5.4.2.
