### ISSUE TITLE
Language and Text Overriding Not Working as Documented

### ISSUE THREAD

**Issue by BrandonSchreck** [okta/okta-signin-widget#980] opened 2019-12-10 01:09 UTC
### I'm submitting a
  - [x] bug report
### Background info
In v2.16, users had the ability to [override certain text properties](https://github.com/okta/okta-signin-widget/tree/okta-signin-widget-2.16.0#language-and-text) through the OktaSignIn constructor. After upgrading to v3.5 (also seen as early as v3.1), this functionality doesn't seem to work the same.

The documentation points to the [login.properties](https://github.com/okta/okta-signin-widget/blob/master/packages/@okta/i18n/src/properties/login.properties) for a full list of properties that can be overwritten. However, when I attempt to override the 'primaryauth.username.placeholder', the label above the input field is affected instead of the placeholder value. 

Additionally, I was previously able to customize the tooltip verbiage, but the latest version doesn't appear to have a tooltip.

I've created two examples demonstrating the before and after:

v2.16 - https://jsfiddle.net/bschreck86/n7q5z823/
**HTML output**
```html
<div data-se="o-form-fieldset" class="o-form-fieldset o-form-label-top">
	<div data-se="o-form-input-container" class="o-form-input">
		<span data-se="o-form-input-username" class="o-form-input-name-username o-form-control okta-form-input-field input-fix">
			<span class="input-tooltip icon form-help-16" data-hasqtip="0"></span>
			<span class="icon input-icon person-16-gray"></span>
			<input type="text" placeholder="Email Address" name="username" id="okta-signin-username" value="" aria-label="Email Address" autocomplete="off">            
		</span>
	</div>
</div>
```

v.3.5 - https://jsfiddle.net/bschreck86/43qauroz/
**HTML output**
```html
<div data-se="o-form-fieldset" class="o-form-fieldset o-form-label-top margin-btm-5">
	<div data-se="o-form-label" class="okta-form-label o-form-label">
		<label for="okta-signin-username">Email Address&nbsp;</label>
	</div>
	<div data-se="o-form-input-container" class="o-form-input">
		<span data-se="o-form-input-username" class="o-form-input-name-username o-form-control okta-form-input-field input-fix">
			<input type="text" placeholder="" name="username" id="okta-signin-username" value="" aria-label="" autocomplete="off">
		</span>
	</div>
</div>
```

### Expected behavior
Overriding the placeholder/tooltip text should affect the input field's placeholder value and the value seen when one hovers over the tooltip.

### What went wrong?
The tooltip is missing completely and the input field is missing the overwritten placeholder property.

### Steps to reproduce
Please find an example here:
https://jsfiddle.net/bschreck86/43qauroz/

### Your environment
  - Okta Sign-In Widget Version: 3.5.0
  - Browser: Chrome

**Comment by haishengwu-okta** [comment] 2019-12-10 16:58
Thanks for reporting. 
We removed placeholder at [3.0](https://github.com/okta/okta-signin-widget/releases/tag/okta-signin-widget-3.0.0)

```
Updates inputs to use labels instead of placeholders (#706, #744)
```

**Comment by BrandonSchreck** [comment] 2019-12-10 17:11
@haishengwu-okta, did tooltips go away as well?

**Comment by haishengwu-okta** [comment] 2019-12-10 17:23
@BrandonSchreck yes. https://github.com/okta/okta-signin-widget/pull/718

**Comment by swiftone** [comment] 2020-01-06 22:20
Closing as working as intended.  If there is an unanswered problem with this, feel free to reopen with more details.

**Closed by swiftone** 2020-01-06 22:20 UTC
Labels: awaiting-response

**Comment by panmanphil** [comment] 2020-02-28 20:12
The live widget tool that is linked from the documentation is using an older version of the widget and the old tooltip behavior works as it did before. Wasted a bunch of time trying to figure what i was doing wrong getting this new "explain" line instead of a tooltip. Really should update that.
