### ISSUE TITLE
rememberDevice.timebased setting not visible in 6.5.0

### ISSUE THREAD

**Issue by estoel81** [okta/okta-signin-widget#2636] opened 2022-07-27 07:42 UTC
### Describe the bug

We migrated from 5.x.x to 6.5.0 and now it's not possible to remember the device for x time. Was this functionality removed or is it a bug? 

Is it missing the rememberDevice.timebased property in the settings? Or is this a missconfiguration

### What is expected to happen?

Show the rememberDevice.timebased box
![image](https://user-images.githubusercontent.com/17541712/181189847-7f3e1e6e-16c7-4f9a-a40f-29bf1ca21b8c.png)

### What is the actual behavior?

Missing checkbox
![image](https://user-images.githubusercontent.com/17541712/181189890-c256aeb0-71ad-490e-b675-fceb7ea64301.png)

### Reproduction Steps

-

### SDK Versions

"@okta/okta-signin-widget": "6.5.0",

### Execution Environment

Chrome, NL-nl, angular 13

**Comment by oleksandrpravosudko-okta** [comment] 2022-07-27 11:02
Thanks for the report @estoel81.
We will investigate this. Internal ref: OKTA-518397

**Comment by BassplayerPatrick** [comment] 2022-07-29 14:27
@estoel81 we tested it with version 6.6.0 and it appears that it's caused by configuration of the sign-in rule in Okta. Context: we've experimented with passwordless logins which require Factor sequence. When MFA is configured with a Factor sequence, the checkbox will not be rendered anymore.

@oleksandrpravosudko-okta I guess you can close this issue

**Closed** 2022-08-01 07:12 UTC
Labels: bug
