### ISSUE TITLE
Success callback of renderEl not executed when using npm version >1.9.0 

### ISSUE THREAD

**Issue by mwld** [okta/okta-signin-widget#263] opened 2017-07-17 11:29 UTC
With the most recent npm version 1.13.0 (as well as 1.12.0 and 1.11.0) the success callback is not being executed although the "authn" request responds with an object containing ```status: "SUCCESS"```.

1. With the exact same code and using the CDN version (1.13.0) the success callback is being called.
1. When using npm version 1.9.0 it is also working fine.

Setup:
- webpack 2.6.1
- importing via ```import OktaSignIn from "@okta/okta-signin-widget";``` (Note: Using ```var OktaSignIn = require('@okta/okta-signin-widget');``` as mentioned in the [docs](https://github.com/okta/okta-signin-widget#using-the-npm-module) makes no difference.)
- code:
```
const oktaSignIn = new OktaSignIn({ baseUrl: "..." });

oktaSignIn.renderEl(
    { el: "..." },
    (response) => {
        console.log(response); // Not being called
    ...
```

**Comment by k1ch** [comment] 2017-08-21 19:18
I have the same problem.

**Comment by vic10us** [comment] 2017-10-23 18:09
same here.

**Comment by vic10us** [comment] 2017-10-23 18:16
Seems that if I use the minified version it works...
Works: 
`import * as OktaSignIn from '@okta/okta-signin-widget/dist/js/okta-sign-in.min.js';`
Fails: 
`import * as OktaSignIn from '@okta/okta-signin-widget';`

**Comment by lboyette-okta** [comment] 2017-11-30 19:10
This should be resolved with `2.5.0`. You can import directly:

```
import * as OktaSignIn from '@okta/okta-signin-widget';
```

**Closed by lboyette-okta** 2017-11-30 19:10 UTC

**Comment by crazyman1979** [comment] 2017-12-12 15:56
Still getting this issue in 2.5

**Comment by lboyette-okta** [comment] 2017-12-12 18:26
@crazyman1979 What's your environment (angular/react/vue/webpack version)?

**Comment by jpotterpath** [comment] 2018-01-23 19:53
The issue is reproducible with the following JavaScript. I'm also NOT using the NPM version. I'm using the following: 

```html
<script src="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.5.0/js/okta-sign-in.min.js" type="text/javascript"></script>
<link href="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.5.0/css/okta-sign-in.min.css" type="text/css" rel="stylesheet"/>
<link href="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.5.0/css/okta-theme.css" type="text/css" rel="stylesheet"/>

```

```javascript
var oktaSignIn = new OktaSignIn({
    baseUrl: 'https://dev-XOXOXO.oktapreview.com',
    clientId: 'XOXOXO',
    authParams: {
        issuer: 'https://dev-XOXOXO.oktapreview.com/oauth2/default',
        responseType: ['token', 'id_token'],
        display: 'page'
    }
});

function ready(fn) {
    if (document.attachEvent ? document.readyState === "complete" : document.readyState !== "loading") {
        fn();
    } else {
        document.addEventListener('DOMContentLoaded', fn);
    }
}

function renderEl() {
    oktaSignIn.renderEl(
        {el: '#okta-login-container'},
        function success(res) {
            console.log('Does Not Reach', res);
        },
        function error(err) {
            console.error(err);
        }
    );
}

ready(renderEl);
```

**Comment by lboyette-okta** [comment] 2018-01-23 22:51
@jpotterpath Thanks for your example! What's happening is expected in your case, because there's a full-page OIDC redirect. Here's code that does work for that flow:

```javascript
<script src="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.5.0/js/okta-sign-in.min.js" type="text/javascript"></script>
<link href="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.5.0/css/okta-sign-in.min.css" type="text/css" rel="stylesheet"/>
<link href="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.5.0/css/okta-theme.css" type="text/css" rel="stylesheet"/>

<body>
  <div id="okta-login-container"></div>
</body>

<script>
var oktaSignIn = new OktaSignIn({
  baseUrl: 'https://dev-217222.oktapreview.com',
  clientId: '0oacepm3kxoNH43Q10h7',
  authParams: {
    issuer: 'https://dev-217222.oktapreview.com/oauth2/default',
    responseType: ['token', 'id_token'],
    display: 'page'
  }
});

function ready(fn) {
  if (document.attachEvent ? document.readyState === "complete" : document.readyState !== "loading") {
    fn();
  } else {
    document.addEventListener('DOMContentLoaded', fn);
  }
}

function renderEl() {
  oktaSignIn.renderEl(
    {el: '#okta-login-container'},
    function success(res) {
      console.log('Does Not Reach', res);
    },
    function error(err) {
      console.error(err);
    }
  );
}

if (oktaSignIn.tokenManager.get('idToken')) {
  console.log('logged in');
} else if (oktaSignIn.token.hasTokensInUrl()) {
  oktaSignIn.token.parseTokensFromUrl(
    function success(res) {
      res.forEach(function(token) {
        if (token.accessToken) {
          oktaSignIn.tokenManager.add('accessToken', token);
        } else if (token.idToken) {
          oktaSignIn.tokenManager.add('idToken', token);
        }
      });
      console.log('parsed tokens and logged in');
    },
    function error(err) {
      console.error('error', err);
    }
  );
} else {
  ready(renderEl);
}
</script>
```

**Comment by jpotterpath** [comment] 2018-01-23 23:11
HAHA fantastic. That was going to be my feedback .. that the success never gets fired because the redirect happens before that would even happen. Thank you for clarifying! 

You all have been great BTW! Personally I'm an auth n00b and learning a great deal experimenting with Okta. So thank y'all for being so responsive and helpful!

**Comment by vigneshTheDev** [comment] 2018-09-19 05:29
@lboyette-okta, Is there any way to prevent the reload and just call the callback?
