### ISSUE TITLE
The spinner endless rounds

### ISSUE THREAD

**Issue by Aleksandr-Sidorik** [okta/okta-signin-widget#867] opened 2019-09-11 13:46 UTC
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info
When I fill fields with incorrect data the error appears and the spinner under the logo. The spinner starts to round and doesn't stop.
![spiner (copy)](https://user-images.githubusercontent.com/55195110/64956273-e62c5280-d892-11e9-825a-cb7f0decdb2a.png)

### Expected behavior

The spinner appears for a few seconds before the error text appear and disappears after the error is shown.

### What went wrong?

Please provide log or error messages if applicable.

### Steps to reproduce

We have Okta auth page linked with our application.
1. Go to the Sign-in page.
2. Fill fields with incorrect info.
3. Press 'Sign-in' button

### Your environment

  - Okta Sign-In Widget Version: 3 (latest)
  - Browser: Google Chrome 72.0.3626.119
  - OS: Linux Mint 18.3
  - Language: English

**Comment by GinoPane** [comment] 2019-09-11 20:01
More information about the issue:

- it happens on the app-provisioned form; the error is not reproducible on a form when you access it directly (without client id, redirect uri, etc);
- it happens on a default Okta form (the screenshot shows customized form, but the error is the same for the default one).
- it is not an option to simply hide the spinner using CSS, because after re-submit it does not reappear after that; I suppose some kind of application state is messed up and need to be toggled.

**Comment by swiftone** [comment] 2019-09-18 21:47
We're unable to reproduce this (in my tests the spinner vanishes as expected).  Can you offer a more concrete example/reproduction?  Does this only occur on Linux?

What is the "incorrect" info you are supplying (invalid user vs bad password)

Based on your screenshot, that LOOKS like a failure to load the security image.  Does the JS console reveal any errors?  If you load the page with the "Network" debugging console open, do you see a failure to load an image?

**Comment by GinoPane** [comment] 2019-09-27 07:51
Hi!

The security image feature is disabled.

It does not depend on the system.

The incorrect info is a combination of incorrect login and/or password. So, you can use a correct login and incorrect password. Or incorrect login and correct password. Whatever.

Again, the detailed information was provided already:

> it happens on the app-provisioned form; the error is not reproducible on a form when you access it directly (without client id, redirect uri, etc);

**Comment by swiftone** [comment] 2019-10-14 21:17
Internal reference: OKTA-255322

**Comment by KostiantynDrozd-okta** [comment] 2021-01-27 13:42
@GinoPane @Aleksandr-Sidorik @nodediggity 
Thanks for your reports!
Seems, this issue is not reproducible anymore in latest versions of the SIW. I tried to reproduce it using 5.2.2, 5.2.3 versions, but it works as expected.
I'm going to close this issue. In case issue is reproducible, feel free to re-open (or ask new questions in new issues).

**Closed by KostiantynDrozd-okta** 2021-01-27 13:42 UTC
