### ISSUE TITLE
after upgrading from 3.8.2 "need help signing in" link no longer appears

### ISSUE THREAD

**Issue by jdwilkin** [okta/okta-signin-widget#1362] opened 2020-08-04 21:33 UTC
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Describe your issue or request here (if necessary).

On version 4.3.0 the "need help signing in" link doesn't appear on the widget.  
 

### What went wrong?

"Need help signing in" link is missing.  I have inspected the dom and the anchor element exists but without any text

### Steps to reproduce

I just upgraded from 3.8.2 to 4.3.0

### Your environment

  - Okta Sign-In Widget Version: 4.3.0
  - Browser: chrome
  - Framework: react
  - OS: windows
  - Language: typescript

**Comment by swiftone** [comment] 2020-08-04 21:51
@jdwilkin - Thanks for the report.  I'm checking with the teams involved and hope to have some information for you soon.

**Comment by jdwilkin** [comment] 2020-08-04 22:27
to save some time I got to this point in the debugger:

`            return '<a href="#" data-se="needhelp" aria-expanded="false" aria-controls="help-links-container" class="link help js-help">' + u((c(n, "i18n") || t && c(t, "i18n") || l).call(s, {
              name: "i18n",
              hash: {
                bundle: "login",
                code: "needhelp"
              },
              data: i,
              loc: {
                start: {
                  line: 1,
                  column: 116
                },
                end: {
                  line: 1,
                  column: 155
                }
              }
            }))`

and both objects that are looking for an "i18n" key don't have one leaving the template without any text.  trying to debug with a .min file isn't straight-forward so I wasn't able to determine why there was no "i18n" member.

**Comment by swiftone** [comment] 2020-08-04 23:39
I'm unable to replicate this issue with a minimal set up - are you changing or setting any i18n values?

**Comment by jdwilkin** [comment] 2020-08-05 15:24
nope, I am not changing anything I just upgraded as specified in my report... here is the entirety of my signin react component:

    import React, { Component } from 'react';
    import ReactDOM from 'react-dom';
    
    import OktaSignIn from '@okta/okta-signin-widget';
    import '@okta/okta-signin-widget/dist/css/okta-sign-in.min.css';
    import logo from 'assets/logo_footer.png';
    
    interface Props {
        baseUrl: string;
        onSuccess: any;
        onError: any;
    }
    
    class OktaSignInWidget extends Component<Props> {
        private widget: any;
    
        componentDidMount() {
            const el = ReactDOM.findDOMNode(this);
            this.widget = new OktaSignIn({
                baseUrl: this.props.baseUrl,
                language: 'en',
                logo: logo,
                brandName: 'My Brand',
                colors: {
                    brand: '#54565A',
                },
                authParams: {
                    pkce: false,
                },
            });
            this.widget.renderEl({ el }, this.props.onSuccess, this.props.onError);
        }
    
        componentWillUnmount() {
            try {
                this.widget.remove();
            } catch (e) {
                // this for some reason throws on occasion
            }
        }
    
        render() {
            return <span />;
        }
    }
    
    export default OktaSignInWidget;

**Comment by jdwilkin** [comment] 2020-08-05 20:45
After some digging two things are clear... in the settings object even though "i18n" is defined in the "local" (I assume this is the standard place to set defaults), it never actually gets assigned.  This might be normal however since it seems that "i18n" is actually stored in the "Bundles" object (which appears to be loading correctly).  That being said I can't see where the "bundles" are used to satisfy the templates.  Keep in mind all of this is the result of a naive investigation looking at minified javascript files, so I am sure I am missing obvious things.  The result however is clear that NONE of the "i18n" items are being resolved in my widget.

**Comment by swiftone** [comment] 2020-08-05 21:11
Thanks for the update - I'll pass your findings on to the dev working on our handlebars integration in the widget and see if we can find an answer.  (our internal tests DO render this successfully, so something is odd).

**Comment by aarongranick-okta** [comment] 2020-08-06 01:00
@jdwilkin Thank you for the report! I have been able to reproduce the issue in version 4.2.3 and version 4.3.0. I recommend using version 4.2.2 until we can release a fixerd version (4.2.3, 4.3.1). This should happen this week.

**Comment by igcherkaev** [comment] 2020-08-06 15:01
@aarongranick-okta I also noticed that with version 4.2.3 and 4.3.0 as soon as I attempt to override anything under i18n, the fields just disappear from the widget and renders it unusable completely. Had to revert to 4.2.2.

**Comment by aarongranick-okta** [comment] 2020-08-06 17:17
@igcherkaev Thanks Igor, we are seeing this as well with 4.2.3+. We have a fix ready, it should be released today as 4.2.4 and 4.3.1

**Comment by aarongranick-okta** [comment] 2020-08-07 00:23
@igcherkaev We have released new versions `4.2.4` and `4.3.2` which should resolve this issue. This one had slipped through our normal testing because it only affected the NPM module and, aside from the missing help link, only broke if using custom translations. We have added additional testing to prevent a regression. Thanks again for bringing it to our attention!

**Comment by aarongranick-okta** [comment] 2020-08-07 15:19
@jdwilkin Thanks again for the error report. This issue should be fixed now in the latest versions of the widget.

**Closed by aarongranick-okta** 2020-08-07 15:19 UTC

**Comment by devopsmica** [comment] 2020-08-20 14:52
Well, I don't know if it's related, but with version 4.3.2, now my french language pack isn't picked from the source, but try to be fetched from okta CDN and it's not found...

**Comment by aarongranick-okta** [comment] 2020-08-20 17:22
@devopsmica This sounds like a different issue, do you mind creating a new issue here on GitHub? Please also specify if it worked in an earlier version, and what that version was, so we can see where the regression happened. Thanks!
