### ISSUE TITLE
Error ‘AuthSdkError: The redirectUri passed to /authorize must also be passed to /token

### ISSUE THREAD

**Issue by umerkk** [okta/okta-signin-widget#1233] opened 2020-06-11 18:34 UTC
### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

When using the latest Okta-Signing-widget & PKCE workflow, I am getting this error in the callBackComponent "Error ‘AuthSdkError: The redirectUri passed to /authorize must also be passed to /token".

The issue persists even after assigning the redirectURI to the constructor of the widget. My Configuration is as below:
      baseUrl:  environment.oktaConfig.issuer.split('/oauth2')[0],
      clientId: environment.oktaConfig.clientId,
      redirectUri: environment.oktaConfig.redirectUri,
      authParams: {
        pkce: true,
        responseMode: 'query',
        issuer: environment.oktaConfig.issuer,
        clientId: environment.oktaConfig.clientId,
        redirectUri: environment.oktaConfig.redirectUri,
        scopes:[openid, profile, email]
      },

Although what I observed is, if I override the okta-auth-js library to V3.0.0, the code starts working fine but somehow it doesn't work with V3.1.X

Upon looking into the code of Okta-auth-js, the redirectUri should be passed as obj key within the AuthParams.

### Your environment

  - Okta Sign-In Widget Version: 3.8.2
  - Browser: Chrome
  - OS: Mac
  - Language: English

**Comment by aarongranick-okta** [comment] 2020-06-12 19:16
Duplicate of: https://github.com/okta/okta-auth-js/issues/398

**Closed by aarongranick-okta** 2020-06-12 19:16 UTC
