### ISSUE TITLE
country / language assets cannot be found

### ISSUE THREAD

**Issue by BassplayerPatrick** [okta/okta-signin-widget#1038] opened 2020-02-10 15:59 UTC
using the latest update of the okta-signin-widget, version 3.7.1, some warnings appear in the console about some language and country related jsonp files that cannot be found.

for instance: the following should be able for download, but doesn't exist:

https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/3.7.1/labels/jsonp/country_de.jsonp?callback=jsonp_country

https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/3.7.1/labels/jsonp/login_nl_NL.jsonp?callback=jsonp_login

Please fix ASAP

**Comment by haishengwu-okta** [comment] 2020-02-10 16:38
@BassplayerPatrick 
You're suppose to use link like `https://global.oktacdn.com/okta-signin-widget/3.1.0/js/okta-sign-in.min.js`. Please check https://github.com/okta/okta-signin-widget#using-the-okta-cdn

**Comment by BassplayerPatrick** [comment] 2020-02-10 17:19
Incorrect. I'm not downloading the widget, the widget downloads the assets,
which are unavailable. It's not customizable code.

Op ma 10 feb. 2020 17:38 schreef Haisheng Wu <notifications@github.com>:

**Comment by haishengwu-okta** [comment] 2020-02-10 19:07
@BassplayerPatrick How do you load/initialize widget in your page?

**Comment by BassplayerPatrick** [comment] 2020-02-10 23:30
I initialize the widget like in the examples

To be clear. Up until version 3.5.0 this was not an issue. We updated to
3.7.1 without any other changes and encountered this problem.

Op ma 10 feb. 2020 20:07 schreef Haisheng Wu <notifications@github.com>:

**Comment by haishengwu-okta** [comment] 2020-02-11 01:15
@BassplayerPatrick 
- Can you show us the code how you load the widget (not how to initialize it)
    - I bet you loads widget from domain `https://ok1static.oktacdn.com/`
- Your issue will be resolved by itself after several weeks (depends on our release schedule) or you load widget from `https://global.oktacdn.com`. (read my first response please)

**Comment by BassplayerPatrick** [comment] 2020-02-11 04:21
I'm not loading the widget dynamically. I have the package locally. If the
url got changed , then the widget has to be updated with that. I shouldn't
be bothered with it.

Op di 11 feb. 2020 02:15 schreef Haisheng Wu <notifications@github.com>:

**Comment by haishengwu-okta** [comment] 2020-02-11 06:47
@BassplayerPatrick sorry about that. I think I found the root cause now
https://github.com/okta/okta-signin-widget/blob/master/src/models/Settings.js#L39
We'll try to fix as soon as we could.

**Comment by BassplayerPatrick** [comment] 2020-02-11 07:03
Great! Thank you very much

Op di 11 feb. 2020 07:47 schreef Haisheng Wu <notifications@github.com>:

**Comment by BassplayerPatrick** [comment] 2020-02-20 12:51
@haishengwu-okta 
Any update on this issue yet? This is blocking us from updating to the newest version

**Comment by swiftone** [comment] 2020-02-28 21:39
@BassplayerPatrick - Can you check to see if the latest version (3.8.0) of the widget resolves this problem for you?

**Comment by BassplayerPatrick** [comment] 2020-03-09 09:57
@swiftone - My colleague checked with release 3.8.1 and this issue is still not resolved. The widget still ttries to load assets from:
https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/3.8.1/labels/jsonp/login_nl_NL.jsonp?callback=jsonp_login
https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/3.8.1/labels/jsonp/country_nl_NL.jsonp?callback=jsonp_country

which resolve to a 404 NOT FOUND.

**Comment by BassplayerPatrick** [comment] 2020-03-17 12:02
@swiftone Is there any update on this issue yet?

**Comment by swiftone** [comment] 2020-03-20 21:12
@BassplayerPatrick - We've confirmed that patch versions still aren't appearing on the CDN - investigating WHY.

**Comment by svantreeck** [comment] 2020-04-07 22:48
I'm still getting the same error with 3.9 when using its npm package and a non-english language--when switching to es for example, the widget tries and fails to load this url: https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/3.9.0/labels/jsonp/login_es.jsonp?callback=jsonp_login

```ts
import React, { useEffect } from 'react';
import { useOktaAuth } from '@okta/okta-react';
import OktaSignIn from '@okta/okta-signin-widget';


export default function OktaLoginForm() {
    const { authService } = useOktaAuth();
    const signIn = new OktaSignIn({
       language: 'es',
       ...my config...
    });

    useEffect(() => {
        signIn.renderEl(
            {
                el: '#auth-container'
            },
            function success(res) {
                // Successful login
                if (res.status === 'SUCCESS') {
                    authService.redirect({ sessionToken: res.session.token });
                }
            });
    });

    return (
        <div id="auth-container"></div>
    );
}
```

**Comment by swiftone** [comment] 2020-04-10 21:24
Internal ref: OKTA-289861

**Comment by alexvictoor** [comment] 2020-04-14 12:46
Hello all,
I am experimenting the same issue :(
Quite eager to try a fix!

**Comment by haishengwu-okta** [comment] 2020-04-16 22:48
Sorry for the inconvenience.
Before we deploy the fix, could you try the work around by customizing `assets.baseUrl`?

```
  "assets": {
    "baseUrl": "https://global.oktacdn.com/okta-signin-widget/{{yourWidgetVersion}}/"
  },
```

**Comment by BassplayerPatrick** [comment] 2020-04-17 07:49
@haishengwu-okta Yesy, we already had this work-around in place and confirmed that worked.
When will the fix be deployed?

**Comment by alexvictoor** [comment] 2020-04-17 09:17
I have tested as well and it works fine :)

**Comment by svantreeck** [comment] 2020-04-20 16:45
Yeah the workaround works for me as well, thanks!

**Comment by arjenbrandenburgh** [comment] 2020-06-09 18:42
Wanted to let you know that this bug still persists in version 4.1.2 and I have opened up a PR to resolve this.

**Comment by RichiCoder1** [comment] 2020-07-28 17:44
Saw this issue and tried the latest widget version and it appears to be working now!

**Comment by swiftone** [comment] 2020-08-06 22:53
Closing this issue as resolved - if this continues to be a problem for anyone, please open a new issue with details and reference this one.

**Closed by swiftone** 2020-08-06 22:53 UTC
Labels: bug
